spring:
  profiles:
    active: dev
  graphql:
    graphiql:
      enabled: true
    path: /api/graphql

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api-docs