spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/httpserver_data?authSource=admin
  jpa:
    database-platform: org.hibernate.dialect.MongoDialect