spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/testdb?authSource=admin
  jpa:
    database-platform: org.hibernate.dialect.MongoDialect